### ISSUE TITLE
Provide tag for 3.2 and 3.2.1

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot_headers#70]
Godot 3.2 and 3.2.1 has been released so I guess godot_headers should provide those tags now

I personally need this because Godot 3.2 api is not 100% compatible with 3.1 (see https://github.com/godotengine/godot/issues/35464)

**Comment by Croydon** [comment]
Yes, please add tags for the versions. This makes packaging easier and more confident/trustworthy too

**Comment by vnen** [comment]
I added tags for the 3.1 and 3.2 line. Ideally this should be part of the release process which now it's easier since this repo is part of the main org.
