### ISSUE TITLE
ArrayMesh::clear_surfaces API missing from api.json

### ISSUE THREAD

**Issue by ameyp** [godotengine/godot_headers#80]
Godot's documentation says that `ArrayMesh` has a `clear_surfaces` API: https://docs.godotengine.org/en/latest/classes/class_arraymesh.html#class-arraymesh-method-clear-surfaces

But the `api.json` doesn't appear to contain it. I tried generating a new `api.json` from Godot-3.2.2 on Windows and that didn't contain `clear_surfaces` either.

**Comment by sheepandshepherd** [comment]
`clear_surfaces` was added in 4.0. You can switch the docs from the `latest` branch to `stable` to see 3.2.2's API.

[surface_remove](https://docs.godotengine.org/en/stable/classes/class_arraymesh.html#class-arraymesh-method-surface-remove) with a loop over get_surface_count (in the parent class, Mesh) works too.
